{
 "title": "DOLPHINSCHEDULER-DSApiServer",
 "description": "Dashboard for Spring Boot Metrics",
 "tags": [ "DOLPHINSCHEDULER" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values(up{job=~\"DOLPHINSCHEDULER-DSApiServer\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"$JobName\"},instance)"
    }
   },
   {
    "name": "memory_pool_heap",
    "label": "Memory Pool (heap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"heap\"},id)"
    }
   },
   {
    "name": "memory_pool_nonheap",
    "label": "Memory Pool (nonheap)",
    "query": {
     "query": "label_values(jvm_memory_used_bytes{area=\"nonheap\"},id)"
    }
   },
   {
    "name": "pool",
    "label": "Connection Pool",
    "query": {
     "query": "label_values(druid_initial_size,pool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Basic Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DSMasterServer State",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "All Server State",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "up{job=~\"DOLPHINSCHEDULER.*\"}",
     "legendFormat": "{{job}}-{{instance}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(process_uptime_seconds{job=\"$JobName\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$JobName\", instance=~\"$instance\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{job=\"$JobName\", instance=~\"$instance\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Non-Heap Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$JobName\", instance=~\"$instance\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{job=\"$JobName\", instance=~\"$instance\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Process Open Files",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "process_files_open_files{job=\"$JobName\", instance=~\"$instance\"}",
     "legendFormat": "Open Files"
    },
    {
     "expr": "process_files_max{application=\"$application\", instance=~\"$instance\"}",
     "legendFormat": "Max Files"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "avg(process_start_time_seconds{job=\"$JobName\", instance=~\"$instance\"})*1000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_usage{job=\"$JobName\", instance=~\"$instance\"}",
     "legendFormat": "System CPU Usage"
    },
    {
     "expr": "process_cpu_usage{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Process CPU Usage"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_load_average_1m{job=\"$JobName\", instance=~\"$instance\"}",
     "legendFormat": "Load Average [1m]"
    },
    {
     "expr": "system_cpu_count{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "CPU Core Size"
    }
   ]
  },
  {
   "title": "JVM Statistics - Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$memory_pool_heap (heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "repeat": "memory_pool_heap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$JobName\", instance=~\"$instance\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_heap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "$memory_pool_nonheap (non-heap)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 38 },
   "repeat": "memory_pool_nonheap",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"$JobName\", instance=~\"$instance\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "jvm_memory_committed_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Commited"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instance\", application=\"$application\", id=\"$memory_pool_nonheap\"}",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Classes Loaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{job=\"$JobName\",instance=~\"$instance\"}",
     "legendFormat": "Classes Loaded"
    }
   ]
  },
  {
   "title": "Classes Unloaded",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_classes_unloaded_classes_total{job=\"$JobName\", instance=~\"$instance\"}[5m])",
     "legendFormat": "Classes Unloaded"
    }
   ]
  },
  {
   "title": "Direct Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"$JobName\",instance=~\"$instance\", id=\"direct\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"direct\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Mapped Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_buffer_memory_used_bytes{job=\"$JobName\",instance=~\"$instance\", id=\"mapped\"}",
     "legendFormat": "Used Bytes"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instance\", application=\"$application\", id=\"mapped\"}",
     "legendFormat": "Capacity Bytes"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_daemon_threads{job=\"$JobName\",instance=~\"$instance\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": "jvm_threads_live{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Live"
    },
    {
     "expr": "jvm_threads_peak{instance=~\"$instance\", application=\"$application\"}",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "Memory Allocate/Promote",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_memory_allocated_bytes_total{job=\"$JobName\", instance=~\"$instance\"}[5m])",
     "legendFormat": "allocated"
    },
    {
     "expr": "irate(jvm_gc_memory_promoted_bytes_total{instance=~\"$instance\", application=\"$application\"}[5m])",
     "legendFormat": "promoted"
    }
   ]
  },
  {
   "title": "JVM Statistics - GC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Count",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_count{job=\"$JobName\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "GC Stop the World Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(jvm_gc_pause_seconds_sum{job=\"$JobName\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{action}} [{{cause}}]"
    }
   ]
  },
  {
   "title": "HTTP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_count{job=\"$JobName\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(http_server_requests_seconds_sum{job=\"$JobName\", instance=~\"$instance\", exception=\"None\"}[5m]) / irate(http_server_requests_seconds_count{job=\"$JobName\", instance=~\"$instance\", exception=\"None\"}[5m])",
     "legendFormat": "{{method}} [{{status}}] - {{uri}}"
    }
   ]
  },
  {
   "title": "Logback Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {}
   ]
  },
  {
   "title": "INFO logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"$JobName\", instance=~\"$instance\", level=\"info\"}[5m])",
     "legendFormat": "info",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "ERROR logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"$JobName\", instance=~\"$instance\", level=\"error\"}[5m])",
     "legendFormat": "error",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "WARN logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"$JobName\", instance=~\"$instance\", level=\"warn\"}[5m])",
     "legendFormat": "warn",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DEBUG logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"$JobName\", instance=~\"$instance\", level=\"debug\"}[5m])",
     "legendFormat": "debug",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "TRACE logs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 103 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(logback_events_total{job=\"$JobName\", instance=~\"$instance\", level=\"trace\"}[5m])",
     "legendFormat": "trace",
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "DruidCP Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Initial Pool Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(druid_initial_size{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Min Idle Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_min_idle{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Max Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(druid_max_active{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Peak Pooling Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_pooling_peak{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Peak Active Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_active_peak{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Wait Thread Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(druid_wait_thread_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"})"
    }
   ]
  },
  {
   "title": "Pooling Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_pooling_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{application}} {{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 115 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_active_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}",
     "legendFormat": "{{application}} {{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Logic Connect",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 115 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_logic_connect_count{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Logic Close",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_logic_close_count{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Logic Connect - Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_logic_connect_error_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Physical Connect - Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_physical_connect_error_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Physical Connect",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_physical_connect_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Physical Close",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_physical_close_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Pool Not Empty Wait count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "increase(druid_not_empty_wait_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[1m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Pool Not Empty Wait Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(druid_not_empty_wait_millis{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"}[2m]) / rate(druid_not_empty_wait_count{job=\"$JobName\", instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "SQL Execution Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 140 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_execute_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "SQL Execution Error",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 140 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(druid_error_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Start Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 148 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_start_transaction_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Commit Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 148 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_commit_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  },
  {
   "title": "Rollback Transaction Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 148 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(druid_rollback_count{job=\"$JobName\",  instance=~\"$instance\", pool=~\"$pool\"}[2m])",
     "legendFormat": "{{instance}} {{pool}}"
    }
   ]
  }
 ]
}