{
 "title": "HBASE-HMaster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job='HBASE-HMaster'},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - java_lang_Runtime_StartTime{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HMaster Live State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HA State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 },
   "targets": [
    { "expr": "HBase_Master_HAState", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}