{
 "title": "HBASE-HThriftServer2",
 "tags": [ "HBASE" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job='HBASE-HThriftServer2'},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - java_lang_Runtime_StartTime{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TimeInQueue_min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "Hadoop_HBase_TimeInQueue_min{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TimeInQueue_median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "Hadoop_HBase_TimeInQueue_median{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TimeInQueue_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "Hadoop_HBase_TimeInQueue_max{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HThriftServer2 Live State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$JobName\", area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$JobName\", area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}