{
 "title": "HBASE-HMaster",
 "tags": [ "HBASE" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job='HBASE-HMaster'},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_masterStartTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - Hadoop_HBase_masterStartTime{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HA State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "HBase_Master_HAState", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HMaster Live State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_GcCount_Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Hadoop_HBase_GcCount{job=\"$JobName\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of HRegionServer in each state",
   "type": "table-old",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum(Hadoop_HBase_numRegionServers)",
     "legendFormat": "Total"
    },
    {
     "expr": "count(up{job=\"HBASE-HRegionServer\"} == 1) or vector(0)",
     "legendFormat": "Alive"
    },
    {
     "expr": "sum(Hadoop_HBase_numDeadRegionServers) / 2",
     "legendFormat": "Dead"
    },
    {
     "expr": "sum(Hadoop_HBase_numDrainingRegionServers) / 2",
     "legendFormat": "Draining"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_numOpenConnections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_HBase_numOpenConnections{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Holes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Hadoop_HBase_holes", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "DeadRegion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_HBase_deadServerOpenRegions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "OrphanRegion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Hadoop_HBase_orphanRegionsOnFS", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "MergeFailedCount",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Hadoop_HBase_MergeFailedCount", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_heap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$JobName\", area=\"heap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_memory_bytes_used_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"$JobName\", area=\"nonheap\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ServerCrashTime_99_9th",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "quantile_over_time(0.25, Hadoop_HBase_ServerCrashTime_99_9th_percentile{name=\"Master\",sub=\"Server\"}[1h])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg_Hadoop_HBase_QueueCallTime_num_ops",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "avg_over_time(Hadoop_HBase_QueueCallTime_num_ops{job=\"$JobName\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_numActiveScanHandler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "Hadoop_HBase_numActiveScanHandler{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_numActiveReadHandler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "Hadoop_HBase_numActiveReadHandler{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_numActiveWriteHandler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "Hadoop_HBase_numActiveWriteHandler{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_numActiveReplicationHandler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "Hadoop_HBase_numActiveReplicationHandler{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_AppendTime_mean",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "Hadoop_HBase_AppendTime_mean{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Avg_Hadoop_HBase_GcTimeMillis",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg_over_time(Hadoop_HBase_GcTimeMillis{job=\"$JobName\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Hadoop_HBase_averageLoad",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "Hadoop_HBase_averageLoad", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Hadoop_HBase_MergeTime_mean",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "Hadoop_HBase_MergeTime_mean", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}