{
 "title": "HDFS-JournalNode",
 "tags": [ "HDFS" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job=\"HDFS-JournalNode\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JournalNode State",
   "type": "table-old",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_syncs_60s_95th_percentile_latency_micros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60s95thPercentileLatencyMicros",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_syncs_60s_99th_percentile_latency_micros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs60s99thPercentileLatencyMicros",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_syncs_300s_95th_percentile_latency_micros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs300s95thPercentileLatencyMicros",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_syncs_300s_99th_percentile_latency_micros",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_Syncs300s99thPercentileLatencyMicros",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_batches_written_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_BatchesWritten{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nv_bytes_written_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_BytesWritten{instance=\"$instance\"}[1m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "jn_jvm_gc_count_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_GcCount{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_jvm_gc_time_millis_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_JournalNode_GcTimeMillis{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_jvm_mem_nonheap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_MemNonHeapUsedM{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jn_mem_heap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_JournalNode_MemHeapUsedM{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}