{
 "title": "HDFS-NameNode",
 "tags": [ "HDFS" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job='HDFS-NameNode'},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_NNStartedTimeInMillis{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - Hadoop_NameNode_NNStartedTimeInMillis{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of datanode in each state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 11, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_NumInServiceLiveDataNodes)",
     "legendFormat": "Live"
    },
    {
     "expr": "avg(Hadoop_NameNode_NumDecomDeadDataNodes)",
     "legendFormat": "Dead"
    },
    {
     "expr": "avg(Hadoop_NameNode_NumInMaintenanceDeadDataNodes)",
     "legendFormat": "Maintance"
    },
    {
     "expr": "avg(Hadoop_NameNode_NumDecomLiveDataNodes)",
     "legendFormat": "DecomLive"
    },
    {
     "expr": "avg(Hadoop_NameNode_StaleDataNodes)",
     "legendFormat": "Stale"
    },
    {
     "expr": "avg(Hadoop_NameNode_NumEnteringMaintenanceDataNodes)",
     "legendFormat": "EnteringMaintenance"
    },
    {
     "expr": "avg(Hadoop_NameNode_NumDecommissioningDataNodes)",
     "legendFormat": "Decommissioning"
    }
   ]
  },
  {
   "title": "NN State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "FSState",
   "type": "stat",
   "description": "\"FSState\": \"Current state of the file system: 0 (for Safemode) or 1(Operational)\"",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(Hadoop_NameNode_FSState)", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "HA State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 5 },
   "targets": [
    { "expr": "Hadoop_NameNode_HAState", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "nn_dn_total_capacity_remaining",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityRemaining{ name=\"FSNamesystem\",instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_dn_capacity_used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_CapacityUsed{name='FSNamesystem',instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_total_sync_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_TotalSyncCount{name='FSNamesystem'}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_files_created",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_FilesCreated) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_files_appended",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_FilesAppended) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_file_created_ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_CreateFileOps) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_files_deleted",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_FilesDeleted) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_syncs_num_ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_SyncsNumOps) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nn_delete_file_ops",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_DeleteFileOps) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_fsimage_load_time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_FsImageLoadTime",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_pending_edits_count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_PendingEditsCount",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_syncs_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    { "expr": "Hadoop_NameNode_SyncsAvgTime", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "nn_timeout_re_replications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_TimeoutReReplications",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_missing_blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumberOfMissingBlocks",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_total_file_ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Hadoop_NameNode_TotalFileOps", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "nn_fs_pending_replication_blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_PendingReplicationBlocks{name=\"FSNamesystem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nn_fs_under_replicated_blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_UnderReplicatedBlocks{name=\"FSNamesystem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "fs_total_connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_TotalLoad{name=\"FSNamesystem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nn_files_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_FilesTotal{name=\"FSNamesystem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nn_lock_queue_length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_LockQueueLength{name=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_total_sync_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_TotalSyncCount{name=\"FSNamesystem\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_all_dn_volume_failures_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_VolumeFailuresTotal{name=\"FSNamesystem\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "nn_num_active_clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_NumActiveClients",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "fsname_system_stale_data_nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_ScheduledReplicationBlocks{name=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nn_corrupt_blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Hadoop_NameNode_CorruptBlocks", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "nn_capacity_used_non_dfs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(Hadoop_NameNode_CapacityUsedNonDFS) by (datanode)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 },
   "targets": [
    {}
   ]
  },
  {
   "title": "jvm_mem_non_heap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_MemNonHeapUsedM",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_mem_heap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "Hadoop_NameNode_MemHeapUsedM", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_mem_non_heap_max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "Hadoop_NameNode_MemNonHeapMaxM", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_mem_heap_maxM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    { "expr": "Hadoop_NameNode_MemHeapMaxM", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_nn_mem_maxM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    { "expr": "Hadoop_NameNode_MemMaxM", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_nn_thread_new",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Hadoop_NameNode_ThreadsNew", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_nn_threads_runnable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_NameNode_ThreadsRunnable",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_threads_blocked",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "Hadoop_NameNode_ThreadsBlocked", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_nn_threads_waitting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "Hadoop_NameNode_ThreadsWaiting", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "jvm_nn_gc_count_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_NameNode_GcCount[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_gc_time_millis_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_NameNode_GcTimeMillis{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_log_fatal_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_LogFatal) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_log_error_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_LogError) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_log_warn_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_LogWarn) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_nn_log_info_sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_NameNode_LogInfo) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_mem_bytes_used_heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 131 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "jvm_mem_bytes_used_nonheap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\", job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}