{
 "title": "HDFS-DataNode",
 "tags": [ "HDFS" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job=\"HDFS-DataNode\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "dn_capacity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_Capacity{name=\"FSDatasetState\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_dfs_used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_DfsUsed{name=\"FSDatasetState\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_remaining",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_Remaining{name=\"FSDatasetState\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_last_volume_failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_VolumeFailures{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_num_block_cached",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_NumBlocksCached{name=\"FSDatasetState\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_bytes_written_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_BytesWritten{instance=\"$instance\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "datanode_bytes_read_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_BytesRead{instance=\"$instance\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "dn_blocks_written",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksWritten{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_blocks_read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_BlocksRead{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_read_block_op_num_ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_ReadBlockOpNumOps{instance=\"$instance\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "datanode_from_client_total_rate",
   "type": "timeseries",
   "description": "Total number of each operations from different client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_WriteBlockOpNumOps{instance=\"$instance\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_read_block_op_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_ReadBlockOpAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_write_block_op_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_WriteBlockOpAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_heart_beats_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_HeartbeatsAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_heart_beats_total_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_HeartbeatsTotalAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_send_data_packet_blocked_on_network_nanos_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_SendDataPacketBlockedOnNetworkNanosAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "hadoop_hdfs_datanode_fsync_nanos_num_ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_SendDataPacketTransferNanosAvgTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_send_data_packet_blocked_on_network_num_ops_rate",
   "type": "timeseries",
   "description": "Total rate of sending packets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_SendDataPacketBlockedOnNetworkNanosNumOps{instance=\"$instance\"}[2m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_send_data_packet_transfer_nanos_num_ops_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_SendDataPacketTransferNanosNumOps{instance=\"$instance\"}[2m])",
     "legendFormat": "{{_target}}"
    }
   ]
  },
  {
   "title": "dn_jvm_gc_count_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_GcCount{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_jvm_gc_time_millis_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_DataNode_GcTimeMillis{instance=\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_jvm_mem_nonheap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_MemNonHeapUsedM{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dn_mem_heap_usedM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "Hadoop_DataNode_MemHeapUsedM{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}