{
 "title": "KAFKA-KafkaBroker",
 "tags": [ "KAFKA" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job=\"KAFKA-KafkaBroker\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"$JobName\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\"} == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"GlobalTopicCount\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"GlobalPartitionCount\", instance=\"$instance\"} - on(instance) kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\", instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"OfflinePartitionsCount\", instance=\"$instance\"} "
    }
   ]
  },
  {
   "title": "Controller and Followers ",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "kafka_controller_KafkaController_Value{name=\"ActiveControllerCount\", job=\"$JobName\"}"
    }
   ]
  },
  {
   "title": "Partitions Leader and Replica Per Broker",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "kafka_server_ReplicaManager_Value{name=\"LeaderCount\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "count(kafka_server_ReplicaManager_Value{name=\"PartitionCount\"} <= 1) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RequestHandlerAvgIdlePercent",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "repeat": "broker",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kafka_server_KafkaRequestHandlerPool_MeanRate{name=\"RequestHandlerAvgIdlePercent\", instance=\"$instance\"}",
     "legendFormat": "Request handler avg {{instance}}"
    }
   ]
  },
  {
   "title": "MessagesInPerSec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"MessagesInPerSec\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TotalFetchRequestsPerSec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalFetchRequestsPerSec\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "ZookeeperClient Latency",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_server_ZooKeeperClientMetrics_99thPercentile{name=\"ZooKeeperRequestLatencyMs\", instance=\"$instance\"}",
       "legendFormat": "Total {{request}} 99th"
      }
     ]
    },
    {
     "title": "Avg Produce Latency",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg_over_time(kafka_server_DelayedOperationPurgatory_Value{name=\"NumDelayedOperations\", delayedOperation=\"Produce\", instance=\"$instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ResponseSendTimeMs P99",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"ResponseSendTimeMs\",request=\"FetchConsumer\", instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Produce Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=\"Produce\", instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=\"FetchConsumer\", instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "FetchFollow Latency 99th per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_99thPercentile{name=\"TotalTimeMs\",request=\"FetchFollower\", instance=\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Messages In Per Broker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "reqps", "label": "Message/s" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"MessagesInPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes In Per Broker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Produce Message Conversions Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"ProduceMessageConversionsPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Fetch Message Conversions Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"FetchMessageConversionsPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes In Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesInPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Bytes Out Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "Bps", "label": "In (-) / Out (+)" }
     ],
     "targets": [
      {
       "expr": "rate(kafka_server_BrokerTopicMetrics_Count{name=\"BytesOutPerSec\", instance=\"$instance\"}[1m])",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"$job\",instance=~\"$broker\",topic!=\"\"}[1m]))by(instance)",
       "legendFormat": "Bytes In [{{instance}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Troubleshooting",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Failed Produce Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedProduceRequestsPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedFetchRequestsPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Failed Produce Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedProduceRequestsPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Failed Fetch Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_BrokerTopicMetrics_Count{name=\"FailedFetchRequestsPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "ZooKeepe rDisconnects Per Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_SessionExpireListener_Count{name=\"ZooKeeperDisconnectsPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Expires Per Sec",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_server_SessionExpireListener_Count{name=\"ZooKeeperExpiresPerSec\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "ZooKeeper Request Latency Ms P99",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "ms", "label": "Time/ms" }
     ],
     "targets": [
      {
       "expr": "kafka_server_ZooKeeperClientMetrics_99thPercentile{name=\"ZooKeeperRequestLatencyMs\",instance=~\"$instance\"}",
       "legendFormat": "Broker: {{instance}}"
      }
     ]
    },
    {
     "title": "Isr Shrinks Per Sec",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops", "label": "Expands (-) / Shrinks (+)" }
     ],
     "targets": [
      {
       "expr": "sum (irate(kafka_server_ReplicaManager_Count{name=\"IsrShrinksPerSec\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "ISR Shrinks Per Sec"
      },
      {
       "expr": "sum (irate(kafka_server_ReplicaManager_Count{name=\"IsrExpandsPerSec\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "ISR Expands Per Sec"
      }
     ]
    },
    {
     "title": "FetchFollower Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "reqps", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_network_RequestMetrics_StdDev{name=\"ResponseQueueTimeMs\", request=\"FetchFollower\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "FetchConsumer Request Bytes Per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "kbytes", "label": "Request/s" }
     ],
     "targets": [
      {
       "expr": "sum(irate(kafka_network_RequestMetrics_Min{name=\"RequestBytes\", request=\"FetchConsumer\", instance=~\"$instance\"}[1m]))by(instance)",
       "legendFormat": "Request: {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Fetch Purgatory",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_DelayedOperationPurgatory_Value{name=\"NumDelayedOperations\",delayedOperation=\"Fetch\", instance=~\"$instance\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Total Fetch Request Per Broker",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "reqps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "sum (irate(kafka_server_BrokerTopicMetrics_Count{name=\"TotalFetchRequestsPerSec\", instance=\"$instance\"}[1m]))by(instance)",
       "legendFormat": "Broker: {{instance}}"
      }
     ]
    },
    {
     "title": "Offline Log Directory Count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_log_LogManager_Value{name=\"OfflineLogDirectoryCount\", instance=\"$instance\"} ",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Number of Requests Waiting in the Producer Purgatory",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 56 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum (kafka_server_DelayedOperationPurgatory_Value{name=\"NumDelayedOperations\",delayedOperation=\"Produce\",instance=~\"$instance\"})by(instance)",
       "legendFormat": "Broker {{instance}}"
      }
     ]
    },
    {
     "title": "Leader Election Rate And Time Ms",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 56 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_controller_ControllerStats_StdDev{name=\"LeaderElectionRateAndTimeMs\", instance=~\"$instance\"}",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Linux Disk Read Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 65 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort(sum(kafka_server_KafkaServer_Value{name=\"linux-disk-read-bytes\", instance=~\"$instance\"})by(instance))",
       "legendFormat": "Instance Broker:  {{instance}}"
      }
     ]
    },
    {
     "title": "Linux Disk Write Bytes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sort(sum(kafka_server_KafkaServer_Value{name=\"linux-disk-write-bytes\", instance=~\"$instance\"})by(instance))",
       "legendFormat": "Instance Broker:  {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "JVM Threads Current",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_current{job=\"$JobName\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "JVM Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum without(area)(jvm_memory_bytes_used{job=\"$JobName\",instance=~\"$instance\"} )",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s", "label": "Usage/s" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=~\"$JobName\",instance=~\"$instance\"}[5m])",
       "legendFormat": "Broker - {{instance}}"
      }
     ]
    },
    {
     "title": "Time spent in GC",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"$JobName\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}