{
 "title": "LDAP-LDAPExporter",
 "tags": [ "HDFS" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job=\"LDAP-LDAPExporter\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Uptime,cn=Time,cn=Monitor\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "LDAPServer(slapd) State",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "up{job=~\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - openldap_monitored_object{dn=\"cn=Uptime,cn=Time,cn=Monitor\"}) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Current,cn=Connections,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "total_connection",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Total,cn=Connections,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "max_file_descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Max File Descriptors,cn=Connections,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "starting_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Starting,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "active_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Active,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "open_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Open,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "pending_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Pending,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "max_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Max,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "add_operations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Add,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "modify_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Modify,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "delete_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Delete,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "search_operaiontions_per_sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(openldap_monitor_operation{dn=\"cn=Search,cn=Operations,cn=Monitor\", instance=\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "compare_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Compare,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "modrdn_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Modrdn,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bind_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Bind,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "unbind_operaiontions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitor_operation{dn=\"cn=Unbind,cn=Operations,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "max_pending",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Max Pending,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "backload_threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "openldap_monitored_object{dn=\"cn=Backload,cn=Threads,cn=Monitor\", instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}