{
 "title": "SPARK-SparkHistoryServer",
 "tags": [ "SPARK" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job='SPARK-SparkHistoryServer'},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=~\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "SparkHistoryServer Live State",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - java_lang_Runtime_StartTime{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}