{
 "title": "YARN-ResourceManager",
 "tags": [ "YARN" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "JobName",
    "label": "JobName",
    "query": {
     "query": "label_values({job=\"YARN-ResourceManager\"},job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values({job=\"$JobName\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HttpFS Live State",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"$JobName\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "StartTime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "java_lang_Runtime_StartTime{instance=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - java_lang_Runtime_StartTime{instance=\"$instance\"} / 1000)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Number of nodemanager in each state",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_NumActiveNMs)",
     "legendFormat": "Active"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumDecommissioningNMs)",
     "legendFormat": "Decommissioning"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumDecommissionedNMs)",
     "legendFormat": "Decommissioned"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumShutdownNMs)",
     "legendFormat": "Shutdown"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumLostNMs)",
     "legendFormat": "Lost"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumUnhealthyNMs)",
     "legendFormat": "Unhealthy"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_NumRebootedNMs)",
     "legendFormat": "Rebooted"
    }
   ]
  },
  {
   "title": "App running elapsed time",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppsSubmitted)",
     "legendFormat": "Submitted"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsPending)",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsRunning)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsCompleted)",
     "legendFormat": "Completed"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsKilled)",
     "legendFormat": "Killed"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AppsFailed)",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "am_total_launched",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AMLaunchDelayNumOps)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "am_total_registered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AMRegisterDelayNumOps)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "am_avg_launched_registered_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AMLaunchDelayAvgTime)",
     "legendFormat": "AMLaunchDelayAvgTime"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_AMRegisterDelayAvgTime)",
     "legendFormat": "AMRegisterDelayAvgTime"
    }
   ]
  },
  {
   "title": "App running elapsed time",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_running_0)",
     "legendFormat": "running_0(60)"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_running_60)",
     "legendFormat": "running_60(60-300)"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_running_300)",
     "legendFormat": "running_300(300-1440)"
    },
    {
     "expr": "sum(Hadoop_ResourceManager_running_1440)",
     "legendFormat": "running_1440(1440+)"
    }
   ]
  },
  {
   "title": "rm_allocated_memMB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedMB)",
     "legendFormat": "AllocatedMB"
    }
   ]
  },
  {
   "title": "rm_allocated_vcores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedVCores)",
     "legendFormat": "AllocatedVCores"
    }
   ]
  },
  {
   "title": "rm_allocated_containers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AllocatedContainers)",
     "legendFormat": "Containers"
    }
   ]
  },
  {
   "title": "rm_availableMB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableMB)",
     "legendFormat": "AvailableMB"
    }
   ]
  },
  {
   "title": "rm_available_vcores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AvailableVCores)",
     "legendFormat": "AvailableVCores"
    }
   ]
  },
  {
   "title": "rm_pendingMB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_PendingMB)",
     "legendFormat": "PendingMB"
    }
   ]
  },
  {
   "title": "rm_pending_vcores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_PendingVCores)",
     "legendFormat": "PendingVCores"
    }
   ]
  },
  {
   "title": "rm_reservedMB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedMB)",
     "legendFormat": "ReservedMB"
    }
   ]
  },
  {
   "title": "rm_reserved_vcores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_ReservedVCores)",
     "legendFormat": "ReservedVCores"
    }
   ]
  },
  {
   "title": "rm_app_attempt_first_container_allocation_delay_num_ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppAttemptFirstContainerAllocationDelayNumOps)",
     "legendFormat": "AppAttemptFirstContainerAllocationDelayNumOps"
    }
   ]
  },
  {
   "title": "rm_app_attempt_first_container_allocation_delay_avg_time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(Hadoop_ResourceManager_AppAttemptFirstContainerAllocationDelayAvgTime)",
     "legendFormat": "Hadoop_ResourceManager_AppAttemptFirstContainerAllocationDelayAvgTime"
    }
   ]
  },
  {
   "title": "rm_gc_count_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(Hadoop_ResourceManager_GcCount[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "rm_gc_time_rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(Hadoop_ResourceManager_GcTimeMillis[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}